### ISSUE TITLE
Not work with  react-refresh hot reload

### ISSUE THREAD

**Issue by Ridermansb** [mswjs/msw#563] opened 2021-01-23 17:47 UTC
## Describe the bug

Works perfectly.. but if I change something on my code, and the hot reload try to update UI then thrown an error

> index.js?9788:1034 Uncaught RangeError: Failed to construct 'Response': The status provided (0) is outside the range [200, 599].
    at eval (index.js:1057)
    at ServiceWorkerContainer.eval (index.js:1223)
eval @ index.js:1057
eval @ index.js:1223

## Environment

- `msw: ^0.25.0`
- `nodejs: v14.15.3`
- `npm: 6.14.9`
- `@pmmmwh/react-refresh-webpack-plugin: ^0.4.3`
- `react-refresh: ^0.9.0`

> Please also provide your browser version.

Chrome: 88

## To Reproduce

1. Create small react application with `@pmmmwh/react-refresh-webpack-plugin` and `react-refresh: ^0.9.0`
2. Add some browser handles and start it on `index.ts`
3. Start the application in development mode
4. Try to update some component

## Expected behavior
Just update the component and the requests to not be handled by msw

## Screenshots

![image](https://user-images.githubusercontent.com/725337/105609717-e5aaa280-5d89-11eb-87e5-77a050803268.png)

**Comment by lukemorales** [comment] 2021-01-25 13:35
Was about to open an issue on that error, glad to see you've found that the issue is being incompatible with react-refresh!

**Comment by kettanaito** [comment] 2021-01-25 23:40
Hey, @Ridermansb. Thanks for reporting this.

The error message suggests that this issue is similar to #529. The fix for that one has been merged (#564) and will be released soon. 

Would you mind trying the latest `master` of this package to see if your issue is solved?

1. `git clone git@github.com:mswjs/msw.git`.
2. `cd msw`
3. `yarn install`
4. `yarn build`
5. `yarn link`
5. `cd <YOUR_PROJECT>`
6. `yarn link msw && yarn msw init <PUBLIC_DIR>`

Restart your application and ensure that there's no outdated worker error in the console (hard-reload helps).

**Comment by kettanaito** [comment] 2021-01-26 16:48
The issue should be fixed in [`msw@0.26.0`](https://github.com/mswjs/msw/releases/tag/v0.26.0). Please update to that version and follow the worker script update instructions in your browser. Thanks.

**Closed as completed by kettanaito** 2021-01-26 16:48 UTC
Labels: bug, potentially solved, scope:browser
