### ISSUE TITLE
Storybook - Accessing the body object off the request freezes things up

### ISSUE THREAD

**Issue by BryceHayden** [mswjs/msw#456] opened 2020-11-17 15:18 UTC
I followed the recommended setup for storybook, and everything works great until I access data off of the request body. The code below is the main thing I'm trying to get working: 

```
rest.post(`/messages`, (req, res, ctx) => {
    console.log("HERE ----->", Array.isArray(req.body.keys), req.body.keys)
    let response = {}
    //const { keys } = req.body

    //const keys = [...req.body.keys]

    //req.body.keys.forEach((key) => {
    //  response[key] = key.replaceAll(/\./gi, ' ')
    //})

    // for (let i = 0; i < req.body.keys.length; i++) {
    //   keys.push(req.body.keys[i])
    // }    // const response = keys.reduce((acc, current) => {
    //   acc[current] = current.replaceAll(/\./gi, ' ')    //   return acc
    // }, {})    
    return res(
      ctx.status(200),      
      ctx.json(response)
    )
  })
```
Any of the commented out code causes the response to hang, and not return. The window freezes and I have to force close it. 

Node - 14.9.0
Storybook - 6.0.28
MSW - 0.21.3

I'm not sure what else might be needed, as I don't see any errors in the console, in the terminal (storybook just shows everything is normal), and the network just hangs without the response coming back.

**Comment by kettanaito** [comment] 2020-11-18 15:04
Hey, @BryceHayden. Thanks for reaching out.

Could you please provide some additional info regarding the issue:

1. Do you experience this during in-browser development, or during testing? If you're testing, what is the test environment (browser, NodeJS)?
1. Can you `console.log(req.body)` before the problematic code? Perhaps `req.body` is `undefined` at some point, resulting into `req.body.keys` throwing a somehow silenced exception.

**Comment by BryceHayden** [comment] 2020-11-18 18:38
@kettanaito hey thanks for the response. Here's some more information on the issue: 

1. I'm using it in-browser during development. 

2. Yes I can console log it out. It shows up as an Array.

I was able to get this to work: 

```
rest.post(`/messages`, (req, res, ctx) => {
    let response = {}
    req.body.keys.forEach((key, index) => {
        response[index] = 'testing'
    })
    
    console.log("Here is the response", response)

    return res(
      ctx.status(200),      
      ctx.json(response)
    )
  })
```

But as soon as I change it to the following (which assigns the key value to the object), then the response never comes through. I am however able to see the `console.log("Here is the response", response)` in the browser and the object looks like I expect. This breaks the response: 

```
rest.post(`/messages`, (req, res, ctx) => {
    let response = {}
    req.body.keys.forEach((key, index) => {
        response[index] = key
    })
    
    console.log("Here is the response", response)

    return res(
      ctx.status(200),      
      ctx.json(response)
    )
  })
```

So I'm lost as to why I can console log it out but then it cause things to freeze and the API calls never return a response. I'm happy to help track it down in MSW's code but my schedule is pretty hectic at the moment...so a little direction would be helpful.

**Comment by tigerabrodi** [comment] 2020-12-05 20:22
@BryceHayden I would try console logging the `key` within forEach :100:.

**Comment by tigerabrodi** [comment] 2020-12-05 20:23
@kettanaito Don't you also think it should be working if it is possible to assign `response[index]` to `"testing"` :thinking:?

**Comment by timdeschryver** [comment] 2020-12-07 12:45
@BryceHayden  how does the response object look like?
Have you tried changing the parser? for example:

```diff
    return res(
      ctx.status(200),      
-      ctx.json(response)
+      ctx.text(response)
    )
```

**Comment by BryceHayden** [comment] 2020-12-10 07:45
Sorry I've been a little MIA, it has been a busy week at work. I'll try that first thing tomorrow and let you know what I see.

**Comment by BryceHayden** [comment] 2020-12-10 18:19
Okay first off, I need to apologize as I had a small typo in my above comment. Inside of the loop it should have been:

```
response[key] = index 
```
It works fine if you have it the other way. I took some screen shots this time as I thought it might be better than me trying to retype things. 

Okay so this first one is what I see in the network if I change it from `ctx.json` to `ctx.text`

<img width="882" alt="Screen Shot 2020-12-10 at 11 06 39 AM" src="https://user-images.githubusercontent.com/9030892/101812901-3e272880-3ad9-11eb-89ef-541d46fa370e.png">

This next one is what I see in the console log: 

<img width="658" alt="Screen Shot 2020-12-10 at 11 06 56 AM" src="https://user-images.githubusercontent.com/9030892/101812962-51d28f00-3ad9-11eb-8e2b-12fe327b6f4c.png">

Then when I switch it back to `ctx.json` this is what I get in the network, but the console is basically the same. 

<img width="1219" alt="Screen Shot 2020-12-10 at 11 08 44 AM" src="https://user-images.githubusercontent.com/9030892/101813014-6adb4000-3ad9-11eb-9293-619b5aaf89c3.png">


Here's a screen shot of my code...just to make sure that I don't add any more typos.
 
<img width="769" alt="Screen Shot 2020-12-10 at 11 10 03 AM" src="https://user-images.githubusercontent.com/9030892/101813083-7f1f3d00-3ad9-11eb-80bd-144eda8a8e44.png">

**Comment by BryceHayden** [comment] 2020-12-10 18:28
My guess is that it is choking on the object having a key with periods in it. Since the `ctx.text` shows it as [Object Object] It probably thinks I'm using dot notation to access properties on an object.

**Comment by kettanaito** [comment] 2021-02-15 09:07
Thank you for providing more details on that.

I confirm that there is no issue with using property names with dot notation in `ctx.json`:

```js
import { setupWorker, rest } from 'msw'

const worker = setupWorker(
  rest.get('/json', (req, res, ctx) => {
    const key = 'nested.key.name'
    return res(
      ctx.json({
        [key]: true,
      }),
    )
  }),
)

worker.start()
```

The response in the browser:

<img width="1000" alt="Screen Shot 2021-02-15 at 10 05 09" src="https://user-images.githubusercontent.com/14984911/107925964-6ae23b00-6f75-11eb-8b37-f7bf144c408c.png">

It doesn't seem like the issue is with the response body. Try to update to the latest version of MSW and follow any necessary worker script updates (see the instructions in your browser's console on how to do that). Chances are this is already fixed. 

If the issue persists after you update MSW, please create a reproduction repository with this issue.

**Comment by kettanaito** [comment] 2021-02-26 13:31
I'm closing this as I wasn't able to reproduce the issue in an isolated context. Feel free to create a reproduction repository and post it here for us to look at. Until then the issue is simply non-reproducible.

**Closed as completed by kettanaito** 2021-02-26 13:31 UTC
Labels: bug, needs:discussion, scope:browser, needs:reproduction
