### ISSUE TITLE
NS_ERROR_INTERCEPTION_FAILED. Firefox

### ISSUE THREAD

**Issue by mylesdawson** [mswjs/msw#592] opened 2021-02-11 22:33 UTC
## Describe the bug
In Firefox 85.0.2 (64-bit) when in Responsive Design Mode with a responsive device selected (such as "iPad"), endpoints that are not mocked by MSW give a `NS_ERROR_INTERCEPTION_FAILED` Transferred message in the Network tab of devtools. This error occurs after refreshing the page (endpoint called on page load)

## Environment

- `msw: 0.26.2`
- `nodejs: 10.15.3`
- `npm: 6.4.1`
- `react-scripts: 4.0.1`

> Please also provide your browser version.
Firefox 85.0.2 (64-bit)

## To Reproduce
1. Start react app
2. Visit Firefox page that makes a network call
3. Open devtools
4. Enable Responsive Design Mode
5. Select "iPad"
6. Refresh page (assuming network call made on page load)
7. View Network tab in Dev  Tools
8. View 'Transferred' Column and notice the message
9. Click row of failed request and click 'Stack Trace'

## Expected behavior
MSW will not intercept the request, the server will respond with the correct status and data

## Screenshots
Stack Trace:
![image](https://user-images.githubusercontent.com/12759167/107706454-30c32180-6c75-11eb-80a9-9a8fe9bfa932.png)

**Comment by kettanaito** [comment] 2021-02-12 09:27
Hi. @mylesdawson. Thanks for reporting this.

I've followed the steps above and was able to reproduce this in Firefox. It appears you are making a GraphQL request. Since it's not handled with MSW, you expect it to hit an actual endpoint and be performed as-is. 

In the [example project](https://github.com/mswjs/examples/tree/667e5637643ab39eb06681cda8ee461f27760e0b/examples/graphql-react-apollo) I'm trying this, my GraphQL endpoint and the address of my app differ.

- App runs at `http://localhost:3002`
- GraphQL endpoint is `http://localhost:3000`

When I follow those steps I also see a few console errors in the "Console" tab of the DevTools:

```
[MSW] Failed to mock a "POST" request to "http://localhost:3000/graphql": TypeError: NetworkError when attempting to fetch resource.

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://localhost:3000/graphql. (Reason: CORS request did not succeed).

Failed to load ‘http://localhost:3000/graphql’. A ServiceWorker passed a promise to FetchEvent.respondWith() that resolved with non-Response value ‘undefined’.
```

> Response mode seems to have no effect on this issue: it's reproducible either way (FireFox 84.0.2 (64-bit), 85.0.2 (64-bit)).

I also see the `NS_ERROR_INTERCEPTION_FAILED` state of the request in the "Transferred" column of the "Network" tab, just as you've described. 

## Why is this happening? 

I suspect you have a similar setup to mine: your app's address and your GraphQL address differ. When you attempt to perform a bypassed (not mocked) request to your actual GraphQL endpoint, you get a CORS violation. 

Can you please check the console errors and report if there are any? 

## How to fix this? 

Here are some guidelines on [how to avoid CORS errors on localhost](https://medium.com/swlh/avoiding-cors-errors-on-localhost-in-2020-5a656ed8cefa). 

If CORS is the reason, the error isn't specific to the library: you cannot request external resources from localhost, CORS won't allow that. You'd have to set up your app to enable such requests while you're developing locally. Above I've linked but one example of how to do that, you can also find other online. 

## In the case it's not it

> MSW will not intercept the request, the server will respond with the correct status and data

Note that MSW intercepts _all requests_ in the worker, sends them to the client where it decides whether to mock a request or not. This is intentional behavior, otherwise, we won't be able to process all traffic, granting a predictable mocking. Yes, one of the surfaces that would error during a failed request will be the worker, but there's usually more info to that (like the CORS errors indicating what is the real culprit). 

In the case if what I described above isn't applicable to your case, please provide us with the following information:

- How do you make a request (exact client calls)?
- What are the addresses of your app and your GraphQL endpoint you try to hit (the not mocked one)?
- Can you provide a reproduction repository confirming the issue is not CORS?

**Closed as completed** 2021-02-12 09:28 UTC
Labels: bug, scope:browser, api:graphql

**Comment by mylesdawson** [comment] 2021-02-12 17:16
Hi @kettanaito thanks for the quick and detailed response.

Following the guide on how to avoid CORS errors on localhost helped solved the issue on my end. Its interesting that the CORS errors appeared only while in Responsive Design Mode, any idea why that might be the case? One other thing to note was that I was actually making a REST request but ended up with the same console errors as you so the fix was applicable.

Thanks again

**Comment by kettanaito** [comment] 2021-02-13 22:21
I'm glad that you've found the solution!

> Its interesting that the CORS errors appeared only while in Responsive Design Mode, any idea why that might be the case? 

That must have been a coincidence. I could reproduce that issue in the response mode as well as without it. 

> One other thing to note was that I was actually making a REST request but ended up with the same console errors as you so the fix was applicable.

I think the type of request matters little when it comes to CORS. I was lucky to reproduce it quickly with a GraphQL request, but that is still a regular HTTP request. Any requests are subjected to CORS regardless of their API type.
