### ISSUE TITLE
Failed to execute `setupServer` in the environment that is not NodeJS

### ISSUE THREAD

**Issue by brendonco** [mswjs/msw#436] opened 2020-10-26 14:43 UTC
## Environment
using Karma + webpack

| Name | Version |
| ---- | ------- |
"msw" | "^0.21.3",
node | v10.16.3
windows | 10
```js

`26 10 2020 22:24:49.817:DEBUG [Chrome Headless 83.0.4103.116 (Windows 10)]: CONFIGURING -> EXECUTING
Chrome Headless 83.0.4103.116 (Windows 10) ERROR
  An error was thrown in afterAll
  Uncaught Error: [MSW] Failed to execute `setupServer` in the environment that is not NodeJS (i.e. a browser). Consider using `setupWorker` instead.
  Error: [MSW] Failed to execute `setupServer` in the environment that is not NodeJS (i.e. a browser). Consider using `setupWorker` instead.
      at setupServer (webpack-internal:///82:2110:19)
      at eval (webpack-internal:///83:15:49)
      at Object.<anonymous> (context.js:1:1684764)
      at e (context.js:1:110)
      at eval (webpack-internal:///84:5:15)
      at Object.<anonymous> (context.js:1:1686085)
      at e (context.js:1:110)
      at webpackContext (webpack-internal:///85:8:15)
      at Array.forEach (<anonymous>)
      at eval (webpack-internal:///86:3:16)
26 10 2020 22:24:49.882:DEBUG [Chrome Headless 83.0.4103.116 (Windows 10)]: EXECUTING -> CONNECTED
Chrome Headless 83.0.4103.116 (Windows 10): Executed 0 of 0 ERROR (0.066 secs / 0 secs)
26 10 2020 22:24:49.889:DEBUG [launcher]: CAPTURED -> BEING_KILLED
26 10 2020 22:24:49.892:DEBUG [launcher]: BEING_KILLED -> BEING_FORCE_KILLED
26 10 2020 22:24:49.904:DEBUG [karma-server]: Run complete, exiting.
26 10 2020 22:24:49.910:DEBUG [launcher]: Disconnecting all browsers
26 10 2020 22:24:49.912:DEBUG [launcher]: BEING_FORCE_KILLED -> BEING_FORCE_KILLED
26 10 2020 22:24:49.954:DEBUG [proxy]: Destroying proxy agents`


handlers

`
import { rest } from 'msw'

export const handlers = [
    rest.get('/config', (req, res, ctx) => {
        return res(
            ctx.status(200, 'Mocked status'),
            ctx.json({
                services: {
                    platformService: 'https://dummyurl.com'
                },
            })
        )
    }),
]
`

server.js

`
import { setupServer } from 'msw/node'
import { handlers } from './handlers'

// Setup requests interception using the given handlers.
export const server = setupServer(...handlers)
`

spec

`
describe('', () => {
   // Enable API mocking before tests.
    beforeAll(() => server.listen())

    // Disable API mocking after the tests are done.
    afterAll(() => server.stop())

    afterEach(() => server.resetHandlers());


  it('test', async () => {
    const res = await fetchUrl('/config');

    expect(res.services).toBeDefine();
  });

})
`


fetchUrl

`
import 'whatwg-fetch';

export const fetchConfig = (url) => {
    return fetch(url, {credentials: 'same-origin'})
        .then(response => response.json())
        .catch(() => {
            console.error(`Failed data "${url}"`);
        });
};

`

**Comment by kettanaito** [comment] 2020-10-26 19:07
Hey, @brendonco. Thanks for reaching out.

This exception is the result of this internal function resolving to `true`:

https://github.com/mswjs/msw/blob/327b384938b1fdf44e77c5bd79e91b7fab0aaad4/src/utils/internal/isNodeProcess.ts#L5-L18

I'll try to get into reproducing your example with Karma and see what may be wrong. You can take a look why that check resolves in your test.

**Comment by kettanaito** [comment] 2020-10-29 10:38
Judging from the logs you've included, you execute a headless Chrome:

```
26 10 2020 22:24:49.817:DEBUG [Chrome Headless 83.0.4103.116 (Windows 10)
```

If your testing environment is a browser, please use [`setupWorker` API](https://mswjs.io/docs/api/setup-worker) instead, as it's designed to run in a browser.

It looks like your test suite is executed in Chrome, and the library gives you a rightful exception that you shouldn't be using `setupServer` in a browser—that won't do anything meaningful. 

Although your test runner may be executed in NodeJS, your tests are still run in a browser. Please use the right API depending on where _your tests_ are run. 

Let me know if this helps.

**Comment by kettanaito** [comment] 2020-11-06 11:05
I don't have experience with Karma, but from what I can gather it spawns an actual browser. This means you must use `setupWorker` and the aforementioned error should be gone. 

There's an open issue about Karma usage (#447) and it requires a reproduction repository with configured Karma. Please, if you have some time to invest into this it would be incredible. We could also use that repository as an official Karma usage example with MSW.

**Closed as completed by kettanaito** 2020-11-06 11:05 UTC
Labels: bug, scope:node
