### ISSUE TITLE
compose.d.ts not compiling with TypeScript

### ISSUE THREAD

**Issue by chrisabrams** [mswjs/msw#519] opened 2020-12-21 20:00 UTC
## Describe the bug

```
Failed to compile.

node_modules/msw/lib/types/utils/internal/compose.d.ts:3:12
Type error: ',' expected.

  1 | declare type ArityOneFn = (arg: any) => any;
  2 | declare type PickLastInTuple<T extends any[]> = T extends [
> 3 |     ...rest: infer U,
    |            ^
  4 |     argn: infer L
  5 | ] ? L : never;
  6 | declare type FirstFnParameterType<T extends any[]> = Parameters<PickLastInTuple<T>>[any];
```

## Environment

- `msw: 0.24.2`
- `nodejs: 14.9.0`
- `npm: 6.14.7`

> Please also provide your browser version.

N/A

## To Reproduce

Try to compile a TypeScript project that uses MSW. I downgraded to `0.21.2` and it works fine (this was the previous version I was using).

## Expected behavior

I expect the types provided by the library to be valid.

**Comment by kettanaito** [comment] 2020-12-21 21:28
Hey, @chrisabrams. Thanks for reporting this.

This seems to be a duplicate of #491 and #499. Please upgrade your TypeScript to version 4.0.0 or higher to get rid of that type error. If that TS version is not desirable, you can downgrade `msw`, but it's good to stay up-to-date on both libraries. 

It would be great for the library to signal about the TypeScript version it requires. Should it specify `typescript` as `optionalPeerDependency`? 🤔

**Closed as completed by kettanaito** 2020-12-21 21:28 UTC
Labels: bug

**Comment by chrisabrams** [comment] 2020-12-21 22:06
We'll be upgrading to TS v4 soon. GTK about the TS version. I think that's a good question, I don't know what the best answer is as I haven't seen great support for `optionalPeerDependency` in the past. I think just calling out which version of TS is supported on the main page should be fine.
