### ISSUE TITLE
Cannot read property 'json' of undefined

### ISSUE THREAD

**Issue by avinashadluri** [mswjs/msw#762] opened 2021-06-01 08:29 UTC
## Environment

| Name | Version |
| ---- | ------- |
| msw  | 0.29.0   |
| node | 14.6     |
| OS   | mac    |

## Request handlers

```jsx
import { useState, useCallback } from 'react'
import { render, screen, fireEvent } from '@testing-library/react'
import '@testing-library/jest-dom/extend-expect'
import { setupServer } from 'msw/node'
import { rest } from 'msw'

export const server = setupServer(
  rest.post('/login', (req, res, ctx) => {
    const { username } = req.body

    return res(
      ctx.json({
        id: 'f79e82e8-c34a-4dc7-a49e-9fadc0979fda',
        username,
        firstName: 'John',
        lastName: 'Maverick',
      })
    )
  })
)

const LoginForm = () => {
  const [username, setUsername] = useState('')
  const [userData, setUserData] = useState(null)
  const handleUsernameChange = useCallback(event => {
    setUsername(event.target.value)
  }, [])

  const handleFormSubmit = useCallback(
    event => {
      event.preventDefault()
      fetch('/login', {
        method: 'POST',
        body: JSON.stringify({
          username,
        }),
      })
        .then(res => res.json())
        .then(setUserData)
        .catch(error => console.log(error))
    },
    [username]
  )

  if (userData) {
    return (
      <div>
        <h1>
          <span data-testid='firstName'>{userData.firstName}</span>{' '}
          <span data-testid='lastName'>{userData.lastName}</span>
        </h1>
        <p data-testid='userId'>{userData.id}</p>
      </div>
    )
  }

  return (
    <form onSubmit={handleFormSubmit}>
      <div>
        <label htmlFor='username'>Username:</label>
        <input
          id='username'
          name='username'
          value={username}
          onChange={handleUsernameChange}
        />
        <button type='submit'>Submit</button>
      </div>
    </form>
  )
}

beforeAll(() => {
  server.listen()
})

afterEach(() => {
  server.resetHandlers()
})

afterAll(() => {
  server.close()
})

describe('LoginForm', () => {
  it('should allow a user to log in', async () => {
    render(<LoginForm />)
    await fireEvent.change(screen.getByLabelText(/username/i), {
      target: { value: 'johnUser' },
    })

    fireEvent.click(screen.getByRole('button', { name: /submit/i }))

    expect(
      await screen.findByText('f79e82e8-c34a-4dc7-a49e-9fadc0979fda')
    ).toBeInTheDocument()
    expect(await screen.findByText('John')).toBeInTheDocument()
    expect(await screen.findByText('Maverick')).toBeInTheDocument()
  })
})

```
 
And when I run `yarn test`

```
  console.log
    FetchError {
      message: 'invalid json response body at undefined reason: Unexpected end of JSON input',
      type: 'invalid-json'
    }
```
 
<img width="1909" alt="Screen Shot 2021-06-01 at 6 28 14 pm" src="https://user-images.githubusercontent.com/7078078/120291974-35d0dd00-c307-11eb-8871-65c23746d5d5.png">

**Comment by kettanaito** [comment] 2021-06-01 10:06
Hey, @avinashadluri. 

As the error message says, the response JSON body is not a valid JSON. Here's how your response body is composed:

```js
ctx.json({
  id: 'f79e82e8-c34a-4dc7-a49e-9fadc0979fda',
  username,
  firstName: 'John',
  lastName: 'Maverick',
})
```

Of all the properties above, only the `username` is dynamic. Let's look into it closer. You're grabbing `username` from `req.body`, assuming the request body is an object. Now let's check if request body is indeed an object:

```js
fetch('/login', {
  method: 'POST',
  body: JSON.stringify({
    username,
  }),
})
```

Here you're sending a POST request with a stringified JSON body, but you're not specifying the proper `Content-Type` request header to denote that you're sending a JSON object. If this request hit a real server, its body would be treated as text, and this is exactly what happens in your handler: `req.body` is _text_, not an object (you can inspect `console.log(req.body)` in your handler).

Set the correct `Content-Type` header of your request and you'll be able to access `req.body.username`:

```diff
fetch('/login', {
  method: 'POST',
+  headers: {
+    'Content-Type': 'application/json'
+  },
  body: JSON.stringify({
    username,
  }),
})
```

With this header set, MSW will know that you're sending a JSON payload and will parse it into an object that you can later use in your handler under `req.body`.

**Comment by avinashadluri** [comment] 2021-06-01 10:17
Definitely the problem is not with Content-Type.  I added as you mention and still the error is same. I suspect this endpoint is not hitting, I put a console in fetch.then() method and this is the console log of response:

```
 Response {
      size: 0,
      timeout: 0,
      [Symbol(Body internals)]: { body: '', disturbed: false, error: null },
      [Symbol(Response internals)]: {
        url: undefined,
        status: 200,
        statusText: 'OK',
        headers: Headers { [Symbol(map)]: [Object: null prototype] {} }
      }
    }
```

Here is the updated code:

```jsx
import { useState, useCallback } from 'react'
import { render, screen, fireEvent } from '@testing-library/react'
import '@testing-library/jest-dom/extend-expect'
import { setupServer } from 'msw/node'
import { rest } from 'msw'

export const server = setupServer(
  rest.post('/login', (req, res, ctx) => {
    const { username } = req.body
    return res(
      ctx.json({
        id: 'f79e82e8-c34a-4dc7-a49e-9fadc0979fda',
        username,
        firstName: 'John',
        lastName: 'Maverick',
      })
    )
  })
)

const LoginForm = () => {
  const [username, setUsername] = useState('')
  const [userData, setUserData] = useState(null)
  const handleUsernameChange = useCallback(event => {
    setUsername(event.target.value)
  }, [])

  const handleFormSubmit = useCallback(
    event => {
      event.preventDefault()
      fetch('/login', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          username,
        }),
      })
        .then(res => console.log(res))
        .then(setUserData)
        .catch(error => console.log(error))
    },
    [username]
  )

  if (userData) {
    return (
      <div>
        <h1>
          <span data-testid='firstName'>{userData.firstName}</span>{' '}
          <span data-testid='lastName'>{userData.lastName}</span>
        </h1>
        <p data-testid='userId'>{userData.id}</p>
      </div>
    )
  }

  return (
    <form onSubmit={handleFormSubmit}>
      <div>
        <label htmlFor='username'>Username:</label>
        <input
          id='username'
          name='username'
          value={username}
          onChange={handleUsernameChange}
        />
        <button type='submit'>Submit</button>
      </div>
    </form>
  )
}

beforeAll(() => {
  server.listen()
})

afterEach(() => {
  server.resetHandlers()
})

afterAll(() => {
  server.close()
})

describe('LoginForm', () => {
  it('should allow a user to log in', async () => {
    render(<LoginForm />)
    await fireEvent.change(screen.getByLabelText(/username/i), {
      target: { value: 'johnUser' },
    })

    fireEvent.click(screen.getByRole('button', { name: /submit/i }))

    expect(
      await screen.findByText('f79e82e8-c34a-4dc7-a49e-9fadc0979fda')
    ).toBeInTheDocument()
    expect(await screen.findByText('John')).toBeInTheDocument()
    expect(await screen.findByText('Maverick')).toBeInTheDocument()
  })
})
 
```

Is there any compatibility issues with any othe package like React 17, jest ("jest": "^26",) .. ?

**Comment by avinashadluri** [comment] 2021-06-01 10:19
I took @kentcdodds example as it is, but still same error:
https://testing-library.com/docs/react-testing-library/example-intro/

```
FetchError {
      message: 'invalid json response body at undefined reason: Unexpected end of JSON input',
      type: 'invalid-json'
    }
```

Do I need any configuration in jest?

**Comment by avinashadluri** [comment] 2021-06-01 10:22
When server (` server.listen()`) is running in node, how to test whether they are really receiving requests? console logs are not triggered in here:
`  rest.post('/login', (req, res, ctx) => {
console.log(req)
....
`

**Comment by kettanaito** [comment] 2021-06-01 10:35
> Definitely the problem is not with Content-Type. I added as you mention and still the error is same. 

The request header should still be set to form a proper request. You may be experiencing a complex issue. 

If your resolver function is not called, please follow this [Debugging uncaught requests](https://mswjs.io/docs/recipes/debugging-uncaught-requests) guidelines to investigate what's wrong. Setting the "onUnhandledRequest" option is a good start. Also, please ensure you're running the latest version of `msw` (`npm i msw@latest`).

**Comment by avinashadluri** [comment] 2021-06-01 10:50
I am using latest version : `0.29.0`
I used `onUnhandledRequest` like below:
```
server.listen({
    onUnhandledRequest: 'warn',
  })

```

I am modified fetch call to a simple GET request:
```
try {
      const response = await fetch('/login', {
        headers: {
          'Content-Type': 'application/json',
        },
      }) 
      const responseJSON = await response?.json()
      if (response?.ok) {
        setUserData(responseJSON)
      } else {
        console.log(response)
      }
    } catch (e) {
      console.log(e)
    }
```
Still same.... 

I modified fetch call get endpoint to a wrong handler: ` fetch('/login123') ` ...
Still it is not throwing any error or warning..


How do I make sure `msw` is working fine in my project? 

I am running a simple fetch get call and mocking server, why there is too much complication?

**Comment by kettanaito** [comment] 2021-06-01 22:32
Hey, @avinashadluri. I'm sorry to hear you having trouble having MSW set up. 

> Is there any compatibility issues with any other package like React 17, jest ("jest": "^26",) .. ?

There are no known compatibility issues. 

> How do I make sure msw is working fine in my project?

Your setup looks fine to me. The issue must be somewhere else. 

I'd kindly ask you to isolate your usage into a reproduction repository and share it here. Then I can help you, otherwise, it's just a guessing game.

**Comment by avinashadluri** [comment] 2021-06-02 00:14
Sure. But please let me know one thing,  we are already using `global.fetch = require('jest-fetch-mock')` in our project and I reset fetch Mocks `fetch.resetMocks()` to stop all mocks for the same handler if any.  Is this the right way ? I suspect existing `jest-fetch-mock` might be affecting msw handlers to respond.

**Comment by kettanaito** [comment] 2021-06-02 12:10
You shouldn't mock `fetch` when using MSW—that's the entire point of using MSW, so you don't mock the underlying implementation directly, or ever. Remove any fetch mocks, ensure you still have a _fetch polyfill_ (i.e. `whatwg-fetch`, setting up which is demonstrated in [this example](https://github.com/mswjs/examples/tree/master/examples/with-jest)).

**Comment by kettanaito** [comment] 2021-06-16 23:04
I conclude this issue is being caused by using `jest-fetch-mock`. Do not use any fetch mocks while using MSW. Do not confuse fetch mocks with fetch polyfills, which you still need in order to call `fetch` in Node.js. 

Let me know if the issue is fixed once you remove the fetch mock and make the necessary adjustments in your tests.

**Closed as completed by kettanaito** 2021-06-16 23:04 UTC
Labels: bug, scope:node, needs:reproduction
