### ISSUE TITLE
Slow requests for non-mocked resources

### ISSUE THREAD

**Issue by lifeiscontent** [mswjs/msw#414] opened 2020-10-03 02:00 UTC
## Describe the bug
In our app, we use segment.io for analytics, and in some cases it will take 30 seconds to load the analytics code during a mocked request from msw in Cypress.

any ideas on how to stop this from happening? or just tell msw to not touch any requests it doesn't mock?

## Environment

- `msw: 0.0.0`
- `nodejs: 0.0.0`
- `npm: 0.0.0`

> Please also provide your browser version.

**Comment by kettanaito** [comment] 2020-10-03 08:19
Hey. Please could you provide an example repo? Chances are the setup of MSW an Cypress you have may be inefficient. We are working on a better integration, and seeing your reproduction repo would be a tremendous help.

**Comment by kettanaito** [comment] 2020-10-03 08:20
Is this related to #405?

**Comment by lifeiscontent** [comment] 2020-10-03 20:40
@kettanaito I tried reproducing the issue I'm seeing in our production app. #405 definitely looks related.

I spent time building out an example, so if you want to see how I would go about testing an app with msw, cypress and next.js take a look here: https://github.com/lifeiscontent/msw-next (again, I can't seem to reproduce the issue in this code)

**Comment by hwstovall** [comment] 2020-11-11 13:40
@lifeiscontent, I wanted to mention that I'm seeing this when I attempt to test an Express application with Jest.

When I run the server normally, both mocked and non-mocked requests are quick. However, something about running them in Jest seems to cause them to go incredibly slow or even timeout. I will put together a basic repo to recreate this, but I wanted to go ahead and mention that I'm seeing this outside of Cypress.

**Comment by lifeiscontent** [comment] 2020-11-11 15:35
@hwstovall Thanks for the heads up! Would love to see a reproduction. The app I experienced this issue on is massive so I didn't know which part of the stack it was coming from. (We're also using express) so if you can create that reproduction that would be a great step forward to getting this fixed!

**Comment by lifeiscontent** [comment] 2020-11-11 15:36
@hwstovall Oh, and for the record I was seeing slowdowns from massive (multiple megabytes of JS) during development. It could be something to do with loading large files.

**Comment by hwstovall** [comment] 2020-11-14 16:08
I just wanted to follow-up on this and say that I was able to isolate the issue down to Axios running under Jest. I updated my code to use node-fetch and it works as intended. I feel like this is more related to other Axios-specific issues that have already been discussed, so I think it's safe to consider this unrelated to the original issue.

**Comment by tigerabrodi** [comment] 2020-12-05 19:57
> I just wanted to follow-up on this and say that I was able to isolate the issue down to Axios running under Jest. I updated my code to use node-fetch and it works as intended. I feel like this is more related to other Axios-specific issues that have already been discussed, so I think it's safe to consider this unrelated to the original issue.

@hwstovall @lifeiscontent @kettanaito Any update on this issue? If it is related to other Axios-specific issues, can this issue be closed?

Thanks! :pray: :smiling_face_with_three_hearts:

**Comment by kettanaito** [comment] 2021-05-12 11:12
Closing this due to the investigation by @hwstovall and the lack of a reliable reproduction example. The issue seems to be connected to Axios.

**Closed as completed by kettanaito** 2021-05-12 11:12 UTC
Labels: bug
