### ISSUE TITLE
Empty URL in resolver.

### ISSUE THREAD

**Issue by olegKusov** [mswjs/msw#434] opened 2020-10-23 16:49 UTC
## Describe the bug
I spent a lot of time to get why my url don't mock. The reason is empty URL.

![image](https://user-images.githubusercontent.com/28058268/97031184-907faa80-1568-11eb-95bd-f294d6808429.png)

 im sending request to /dev/api/v1/auth/login but console.log(req.url) show in terminal empty URL {} object:

![image](https://user-images.githubusercontent.com/28058268/97031274-ad1be280-1568-11eb-852c-539af8af0625.png)

## Environment

- `msw: 0.21.3`
- `nodejs: 14.14.0`
- `npm: 6.14.18`

> Please also provide your browser version.
Im using JEST tests. There is no browser running.

**Comment by marcosvega91** [comment] 2020-10-23 18:07
Hi @olegKusov thanks for reaching us :).

The `req.url` is an instance of [URL](https://developer.mozilla.org/en-US/docs/Web/API/URL). You can access the host with `req.url.host`while the path with `req.url.pathname`. Let me know if this will solve your issue :)

**Comment by olegKusov** [comment] 2020-10-23 19:58
> Hi @olegKusov thanks for reaching us :).
> 
> The `req.url` is an instance of [URL](https://developer.mozilla.org/en-US/docs/Web/API/URL). You can access the host with `req.url.host`while the path with `req.url.pathname`. Let me know if this will solve your issue :)

yes.host is undefined and pathname right. But i don't understand why my pattern doesnt match. I pasted path from pathname

![image](https://user-images.githubusercontent.com/28058268/97048921-7f906280-1583-11eb-8b5f-37d4b35de9c1.png)

**Comment by marcosvega91** [comment] 2020-10-23 20:17
Are you using MSW in a DOM-like environment ? If not it will not work, you should absolute url in this case

https://mswjs.io/docs/getting-started/integrate/node#direct-usage

**Comment by kettanaito** [comment] 2020-10-24 07:51
Hey, @olegKusov. Can you please try the `onUnhandledRequest` option of your server to see what is the actual request, and why they don't match?

```js
const server = setupServer(...)
server.listen({
  onUnhandledRequest: 'warn'
})
```

[Read about it in the docs](https://mswjs.io/docs/api/setup-server/listen#onunhandledrequest)

**Comment by kettanaito** [comment] 2020-10-24 09:02
Could you also provide how do you perform an actual request? 

Most of the mismatch cases are due to a typo, wrong method, or relative URL in a NodeJS environment.

**Comment by olegKusov** [comment] 2020-10-24 22:35
> Hey, @olegKusov. Can you please try the `onUnhandledRequest` option of your server to see what is the actual request, and why they don't match?
> 
> ```js
> const server = setupServer(...)
> server.listen({
>   onUnhandledRequest: 'warn'
> })
> ```
> 
> [Read about it in the docs](https://mswjs.io/docs/api/setup-server/listen#onunhandledrequest)

![image](https://user-images.githubusercontent.com/28058268/97094949-66121800-1662-11eb-8815-70010dbf1eda.png)

**Comment by olegKusov** [comment] 2020-10-24 22:40
> Are you using MSW in a DOM-like environment ? If not it will not work, you should absolute url in this case
> 
> https://mswjs.io/docs/getting-started/integrate/node#direct-usage

I'm using Jest

**Comment by olegKusov** [comment] 2020-10-24 22:43
> Could you also provide how do you perform an actual request?
> 
> Most of the mismatch cases are due to a typo, wrong method, or relative URL in a NodeJS environment.

There is function for requests which wraps axios.
const res = await netPOST<{key: string}>('auth/login', {email, password});

**Comment by kettanaito** [comment] 2020-10-25 07:55
@olegKusov check the end URL you provide to axios. Looks like you compose it dynamically with one of its pieces resolving to `undefined`, thus you see a URL like `http://undefined/` in the console warning. MSW doesn't create requests, only intercepts them, so the misconfigured URL must be coming from your app's logic. 

Otherwise I'd have to see how that abstraction over axios looks like exactly (the `axios` call) to help more.

**Comment by kettanaito** [comment] 2020-10-25 17:25
One of the contributors has discovered an issue in `node-request-interceptor`, when we didn't inherit the default hostname in certain scenarios (https://github.com/mswjs/node-request-interceptor/pull/64). This would also cause a URL like `http://undefined`. Let's keep this in mind until we receive a confirmation from the author on the URL validity on his side.

**Comment by olegKusov** [comment] 2020-10-25 22:30
> @olegKusov check the end URL you provide to axios. Looks like you compose it dynamically with one of its pieces resolving to `undefined`, thus you see a URL like `http://undefined/` in the console warning. MSW doesn't create requests, only intercepts them, so the misconfigured URL must be coming from your app's logic.
> 
> Otherwise I'd have to see how that abstraction over axios looks like exactly (the `axios` call) to help more.

I console.log axios.post route => it's auth/login/
![image](https://user-images.githubusercontent.com/28058268/97120755-83121e00-172a-11eb-9bc5-3848b29305a8.png)
![image](https://user-images.githubusercontent.com/28058268/97120773-9fae5600-172a-11eb-84e3-24c6a190d1a7.png)

**Comment by marcosvega91** [comment] 2020-10-26 06:52
@olegKusov could you please show your `axiosConfig` ?

**Comment by olegKusov** [comment] 2020-10-26 08:02
> @olegKusov could you please show your `axiosConfig` ?

In this case it's empty object.

**Comment by marcosvega91** [comment] 2020-10-26 08:41
I have recreated the issue using a node environment ( no jsdom). The issue will be solved with this PR https://github.com/mswjs/node-request-interceptor/pull/64

**Comment by kettanaito** [comment] 2020-10-26 11:41
The update to `node-request-interceptor` has [been released](https://github.com/mswjs/node-request-interceptor/releases/tag/v0.5.3).

@olegKusov, could you please re-install your dependencies so it gets pulled in and let us know if the issue is gone?

**Comment by olegKusov** [comment] 2020-10-26 13:56
> The update to `node-request-interceptor` has [been released](https://github.com/mswjs/node-request-interceptor/releases/tag/v0.5.3).
> 
> @olegKusov, could you please re-install your dependencies so it gets pulled in and let us know if the issue is gone?

can you please update msw deps and after that i can update my local deps

**Comment by marcosvega91** [comment] 2020-10-26 14:22
@olegKusov could you install the new version of `node-request-interceptor` by running one of the following command:

- `yarn add node-request-interceptor@0.5.3`
      or
- `npm install node-request-interceptor@0.5.3`

**Comment by kettanaito** [comment] 2020-10-26 14:41
You don't need MSW update: it specifies `node-request-interceptor` dependency version range permissive enough to pull in a patched version release:

https://github.com/mswjs/msw/blob/327b384938b1fdf44e77c5bd79e91b7fab0aaad4/package.json#L73

> "^0.5.1" will install "0.5.1" as well as "0.5.3" ("0.5.x")

Neither you should install that 4th party dependency manually. Please reinstall your dependency and the new version of `node-request-interceptor` will be automatically installed. You can verify that by running the following command after the installation:

```bash
$ npm ls node-request-interceptor
```

**Comment by olegKusov** [comment] 2020-10-26 15:57
> You don't need MSW update: it specifies `node-request-interceptor` dependency version range permissive enough to pull in a patched version release:
> 
> https://github.com/mswjs/msw/blob/327b384938b1fdf44e77c5bd79e91b7fab0aaad4/package.json#L73
> 
> > "^0.5.1" will install "0.5.1" as well as "0.5.3" ("0.5.x")
> 
> Neither you should install that 4th party dependency manually. Please reinstall your dependency and the new version of `node-request-interceptor` will be automatically installed. You can verify that by running the following command after the installation:
> 
> ```shell
> $ npm ls node-request-interceptor
> ```

It works! Thank you! I close issue.

**Closed as completed** 2020-10-26 15:58 UTC
Labels: bug, needs:discussion, scope:node, api:rest

**Comment by kettanaito** [comment] 2020-10-26 16:19
Glad to hear that! All props to @sean-hernon for an amazing bug fix 🎉
