### ISSUE TITLE
Having `query` field in XHR json request's body breaks mocks

### ISSUE THREAD

**Issue by pa3** [mswjs/msw#559] opened 2021-01-22 11:29 UTC
## Describe the bug

Sending REST-request with a payload that includes `query` param in a mixed mock setup consisting of both REST and GraphQL mocks results in a `NetworkError` produced by mocks. That only happens when REST-request is being sent via XMLHttpRequest, sending one via fetch API work fine, as far as I was able to observe.

The reason why that fails is that `parse` until from `grapqhl` package throws when being provided with a non-string query to parse (which is the base in the described setup). 

## Environment

- `msw: 0.25.0`
- `nodejs: 14.11.0`
- `npm: 6.14.8`

## To Reproduce

I wrote a reproducing unit-test: https://github.com/pa3/msw/blob/master/test/rest-api/conflict.test.ts

## Expected behavior

The unit test from the previous section runs fine.

## Possible fixes

1. Check `typeof query` somewhere at the beginning of graphql RequestHandler's `parse` handler.
2. Filter out resolvers based on their URL-mask before invoking their `parse` handler, so that requests sent to non-graphql URLs will not mess with graphql handlers logic. 

Let me know what to do you think about these two and I will happily create a PR with one of them.

**Comment by kettanaito** [comment] 2021-01-22 16:05
Hey, @pa3. Thanks for reporting this!

Yes, this is a known issue described in #489. I've also opened a discussion on how to efficiently distinguish between an actual GraphQL request and a compatible counterpart (see https://github.com/mswjs/msw/discussions/535).

> Filter out resolvers based on their URL-mask before invoking their parse handler, so that requests sent to non-graphql URLs will not mess with graphql handlers logic.

You can do this without any changes from the library's side:

```js
import { setupWorker, graphql } from 'msw'

const link = graphql.link('https://api.backend.com/graphql')

setupWorker(
  // All request will first be tested against the endpoint of the link
  // before attempting to parse their query/body.
  link.query('GetUser', resolver)
)
```

> Read more about [GraphQL link](https://mswjs.io/docs/api/graphql/link).

I'll close this issue in favor of the aforementioned one. It's recommended you use `graphql.link` in case of mixed API types setup, as there's no reliable way to tell for sure if a request is a GraphQL request or not.

**Closed as completed by kettanaito** 2021-01-22 16:05 UTC
Labels: bug

**Comment by pa3** [comment] 2021-01-25 12:39
Thanks for such a quick response and sorry for rising a duplicate issue (I was trying to find exiting one, I swear :sweat_smile:). I will   drop some thoughts in  https://github.com/mswjs/msw/issues/489

**Comment by kettanaito** [comment] 2021-01-26 23:38
There's absolutely no worry, @pa3. I know the issue is confusing and I'd like to see it fixed. You bringing it up is but one more reason to think about it more.
