### ISSUE TITLE
How should I use the service worker in jest?

### ISSUE THREAD

**Issue by senadir** [mswjs/msw#170] opened 2020-05-19 14:49 UTC
I'm planning to use this for tests only, so where should I put my serviceWorker file and how will it communicate with my component?

this is the code I'm running for my test (simplified), my component execute some data fetching on mount, this is breaking the test with `window.fetch` is not defined.

```
/**
 * External dependencies
 */
import { rest } from 'msw'
import { setupServer } from 'msw/node'
import { render, fireEvent, waitFor, screen } from '@testing-library/react'
import '@testing-library/jest-dom/extend-expect'
import { CartProvider } from './base-context';
/**
 * Internal dependencies
 */
import CartSidebar from '../cart-sidebar';

describe('CartSidebar', () => {
	const server = setupServer(
		rest.get('*', (req, res, ctx) => {
			return res(ctx.json({ firstName: 'John' }))
		})
	)

  beforeAll(() => {
    // Enable the mocking before all tests
    server.listen()
  })

  it('should render the cart sidebar ', async () => {
	render(
		<CartProvider>
			<CartSidebar />
		</CartProvider>
	)
	const title = screen.getAllByRole('heading');
	expect(title[0].textContent).toEqual('Cart totals')
  })
})
```

**Comment by kettanaito** [comment] 2020-05-19 15:20
Hey, @senadir.

As Service Workers cannot run in a non-browser environment, you don't need to have a Service Worker file if you are planning to use MSW only for Jest tests.

I highly recommend to run `server.close()` in the `afterAll` hook of your test file:

```js
const server = setupServer(...)

beforeAll(() => server.listen())
afterAll(() => server.close())
```

> This makes sure that the patched instances are restored, and the mocked state does not transition to unrelated tests.

The `window.fetch is not defined` error you are experiencing is most likely because `fetch` doesn't exist in Node, so Jest cannot work with your component that calls `fetch()`. This is an expected behavior, and you would have to provide a `fetch` polyfill of your choice. Here are some of the worthy mentions:

- [`whatwg-fetch`](https://github.com/whatwg/fetch)
- [`node-fetch`](https://github.com/node-fetch/node-fetch)
- [`isomoprhic-fetch`](https://github.com/matthew-andrews/isomorphic-fetch)

Pick any of those and require them in your `jest.setup.js` file:

```js
// jest.setup.js
// This ensures you can use `window.fetch()` in your Jest tests.
require('whatwg-fetch')
```

Then provide the path to that setup file in your `jest.config.js` file using the [`setupFiles`](https://jestjs.io/docs/en/configuration#setupfiles-array) option:

```js
// jest.config.js
module.exports = {
  setupFiles: ['./jest.setup.js']
}
```

Let me know if these suggestions helped. I'm closing this, because it doesn't look like an issue with MSW.

**Closed as completed by kettanaito** 2020-05-19 15:20 UTC
Labels: bug

**Comment by kettanaito** [comment] 2020-05-19 15:22
Here's a [usage example](https://github.com/mswjs/examples/tree/de25a897771f1be3b83f62eb1a13e32a5c00b9c8/examples/rest-react) repository that showcases how to use MSW for both unit (Jest) and E2E tests. You may not need the entire setup, but I'm sure you can find some useful references there. 

> Note that it uses Create React App, which provides a `fetch` polyfill out of the box. In case of manual Jest setup one needs to do that manually.

**Comment by adriandmitroca** [comment] 2021-08-20 07:37
@kettanaito 

This is excellent example! Is it possible to separate mocks needed for Jest from mocks needed for web?

**Comment by oteoe** [comment] 2022-09-15 11:12
Would it here make sense that we reroute fetch directly to an MSW handler - without starting the server if the server logic is abstracted - I guess it is since it's working for service workers as well as a nodejs server.

Should not be complicated to write such a helper if that makes sense?

**Comment by kettanaito** [comment] 2022-09-15 11:16
@oteoe, do you have some particular problem in mind you wish to solve with this?

MSW does modules patching already as a part of `server.listen()` (thus the interception):

https://github.com/mswjs/msw/blob/a9b812679ebeb349826be663004508ca6cd6165a/src/node/setupServer.ts#L13-L14

It doesn't patch `fetch` but that's because there's no official support for native Node fetch yet (see https://github.com/mswjs/interceptors/issues/159).
