### ISSUE TITLE
Path Matching: Path with parameters, inconsistent behavior between browser and nodejs

### ISSUE THREAD

**Issue by AriPerkkio** [mswjs/msw#357] opened 2020-08-27 16:09 UTC
I have a handler which works in nodejs but doesn't work in browser. 

## Environment

| Name    | Version |
| ------- | ------- |
| msw     | 0.20.5   |
| browser | 84.0.4147.136 64bit     |
| OS      | Debian 9 + ChromeOS 84.0.4147.136     |

## Request handlers

```js
import { rest} from 'msw';

export const handlers = [
    // Handles GET http://<hash>.server.net/resource
    // This works nodejs but doesnt work for browser
    rest.get('http://*.server.net/resource', (req, res, ctx) => {
        return res(ctx.text('Hello world'));
    }),

    // This works for browser and nodejs
    //rest.get('*.server.net/resource', (req, res, ctx) => {
    //    return res(ctx.text('Hello world'));
    //}),
];
```

## Actual request

```js
fetch('http://randomhashrighthere.server.net/resource')
        .then(response => response.text())
```

## Current behavior

When wildcard is used somewhere between the URL it's not matched with browser's requests. It is however matched in nodejs.

## Expected behavior

Handlers should have exactly the same functionality between browser and nodejs. Path matching should work  identically.

### Reproduce issue
I have set a minimal repo for reproducing the issue: https://github.com/AriPerkkio/msw-path-pattern-issue-repro
```sh
yarn install

# Run tests to validate handler works on nodejs
yarn test

# Start development mode to validate browser doesnt work
yarn start
# Open http://localhost:1234/index.html

# Modify handlers.js and re-check browser
```

If you think this is a valid issue I'm ready to contribute for a fix.

**Comment by kettanaito** [comment] 2020-08-28 09:06
Hey, @AriPerkkio. 

That's an interesting one. Thing is, MSW uses the same library to match request URL in both browser and Node called [`node-match-path`](https://github.com/mswjs/node-match-path). I've also verified that the `http://*.server.net/resource` handler URL matches the `http://randomhashrighthere.server.net/resource` actual URL in the [Path matching REPL](https://mswjs.io/docs/basics/path-matching#repl) on our website.

Thank you for preparing the reproduction repository. I'll check it and update this issue with the findings.

**Comment by kettanaito** [comment] 2020-08-28 09:27
The issue is confirmed as reproducible. 

## Technical insights

When resolving a given mask (request handler first parameter), the library attempts to convert it to a `URL` instance, if possible:

https://github.com/mswjs/msw/blob/b38680dbf258047b7621a2d0256f3d72a3ffcea3/src/utils/matching/matchRequestUrl.ts#L15

https://github.com/mswjs/msw/blob/b38680dbf258047b7621a2d0256f3d72a3ffcea3/src/utils/url/getUrlByMask.ts#L16

During this conversion, `*.server.com/path` is considered a valid URL, however, the asterisk is encoded and produces a URL of the following structure:

```
hash: ""
host: "%2A.server.net"
hostname: "%2A.server.net"
href: "http://%2A.server.net/resource"
origin: "http://%2A.server.net"
password: ""
pathname: "/resource"
port: ""
protocol: "http:"
search: ""
searchParams: URLSearchParams {}
username: ""
```

Since the comparison is encoding-sensitive, `%2A` doesn't match `*`, which results into your request not being matched.

## Solution

I see two potential solutions to this issue:

1. Make path matching encoding-insensitive. 
1. Explicitly short-circuit in `getUrlByMask` and return the given `mask` if it contains an asterisk (`*`). 

I'm leaning forward the second option, because when a mask contains a wildcard it shouldn't be treated as a `URL` instance in the first place. It effectively becomes a special string that resembles a URL but is not such. Performing encoding-insensitive comparison still implies creating a `http://%2A.server.net/resource` URL instance, which gives me a strong reason to believe it may and will cause other issues when the library attempts to treat it as a URL.

**Comment by kettanaito** [comment] 2020-08-28 09:45
We can ensure this doesn't happen by fixing the unit test for path masks:

https://github.com/mswjs/msw/blob/b38680dbf258047b7621a2d0256f3d72a3ffcea3/src/utils/url/getUrlByMask.test.ts#L25-L27

Asterisk (wildcard) alone is indeed not a valid URL. However, if a wildcard if a part of what can be a valid URL, that test would fail.

**Closed as completed** 2020-08-28 11:39 UTC
Labels: bug, scope:browser, api:rest
