### ISSUE TITLE
CAN'T FIND THE ERROR | SynxtaxError: Unexpected end of input

### ISSUE THREAD

**Issue by ReadySoftWARE1** [mswjs/msw#667] opened 2021-03-29 10:06 UTC
### I code a command handler for discord bot today but:
I can't find the error in this code the console says '**SynxtaxError: Unexpected end of input**'
Can you help me find the error.
![Screenshot (2)](https://user-images.githubusercontent.com/81517305/112821450-ec6ad400-90b0-11eb-8d11-4450d5864d0e.png)

**Comment by timdeschryver** [comment] 2021-03-29 11:39
Sorry, but I don't see what the probem is here, and what MSW has to do with it.
Can you elaborate what the problem is?

**Comment by ReadySoftWARE1** [comment] 2021-03-29 12:16
> Sorry, but I don't see what the probem is here, and what MSW has to do with it.
> Can you elaborate what the problem is?

The problem is I cant run the code because of 'SynxtaxError: Unexpected end of input' so the problem is I can't find the error and can't fix the error.

**Comment by kettanaito** [comment] 2021-03-29 12:34
> I can't find the error in this code the console says 'SynxtaxError: Unexpected end of input'

Please provide more information, what you're saying gives us zero insights as to what's happening, less what may be wrong. When you created an issue there was a template that you should've filled. Reciting it for you:

1. Include the version of `msw`: `npm ls msw`.
2. Include your request handlers.
3. Include how you make an actual request.
4. Include what you _expect_ to happen ("there should be no errors" is not an expectation; what do you expect from _your logic_ to do?)

The "Unexpected end of input" most likely means that the response body you're returning is malformed, but it's a wild guess unless you provide the info above. Until there's more info, I'm closing this, since the issue is not at the state to be investigated/discussed. Thanks.

**Closed as completed** 2021-03-29 12:36 UTC
Labels: bug, needs:discussion, scope:node
