### ISSUE TITLE
Bypasses request with "no client" but also outputs to client's console

### ISSUE THREAD

**Issue by hakankaraduman** [mswjs/msw#162] opened 2020-05-18 05:31 UTC
I implemented as shown on the getting started page. It uses the original request instead of the mock because it cannot find client. But it also outputs my debugging console.log to the client's console.

I also see the MSW Enabled log occasionally, not all the times. It also doesn't work with Cypress too I think because of the same issue.

## Environment

- `msw: 0.16.0`
- `nodejs: 12.16.2`
- `npm: 6.14.4`

> Please also provide your browser version.
Google Chrome 81.0.4044.138

## To Reproduce
I don't know how to create a reproducible version of it, sorry. Please guide me if I can do more.

## Expected behavior
Using the mock response.

**Comment by kettanaito** [comment] 2020-05-18 06:29
Hey, @hakankaraduman. Thanks for raising this. 

Can you please share with me:

1. Exact request handlers (`mock.js`) you've used.
1. How are you requiring the `mocks.js` file.
1. How does your request issuing component/code part looks like?

Once I have more info I'd be able to help. Thanks.

**Comment by kettanaito** [comment] 2020-05-22 21:14
Hey, wanted to bump this to double check with you if the issue is still there.

Meanwhile, I've prepared a few [usage examples](https://github.com/mswjs/examples), please try to see if you spot any difference between these and your setup. It may not necessarily be identical, but I hope it can help you narrow down the issue.

**Comment by kettanaito** [comment] 2020-06-03 09:27
I'm closing this for now. Please feel free to update this with the answers to the questions below, I'd be glad to investigate in that case.

It's likely the issue you experience is a result of a race condition between a service worker being ready and your application performing requests. We are working on handling this behavior out of the box (#190), but for now I can recommend to [Defer the start of your app](https://redd.gitbook.io/msw/recipes/deferred-start) until the mocking is ready. That has a high chance of resolving the issue for you.

**Closed as completed by kettanaito** 2020-06-03 09:27 UTC
Labels: bug, scope:browser, needs:reproduction

**Comment by hakankaraduman** [comment] 2020-08-27 09:58
Sorry for long absence, I tried the new versions and it works perfectly for me. Thank you for your work on this package.
