### ISSUE TITLE
GraphQL mock not returning both `data` and `error` in res

### ISSUE THREAD

**Issue by lifeiscontent** [mswjs/msw#410] opened 2020-10-02 00:23 UTC
## Describe the bug
I've got a login mutation that has a response like follows:

```js
    return res(
      ctx.errors([
        {
          message: 'Login failed. Check your email and password',
          locations: [{ line: 2, column: 3 }],
          path: ['signInUser'],
          extensions: {
            code: 'UNAUTHENTICATED',
            fullMessages: [],
            details: [],
          },
        },
      ]),
      ctx.data({ signInUser: null })
    );

```

## Environment

- `msw: 0.21.2`
- `nodejs: 12.18.3`
- `npm: 6.14.6`

> Please also provide your browser version.

## Expected behavior
I'd expect the response of the mock to contain both `data` and `error` keys.

## Screenshots

<img width="609" alt="Screen Shot 2020-10-01 at 5 22 39 PM" src="https://user-images.githubusercontent.com/180963/94875828-b81ca080-040a-11eb-865f-5e8c32ca84b8.png">

**Comment by marcosvega91** [comment] 2020-10-02 21:13
Hi @lifeiscontent thanks for reaching us 😄 

This issue is a duplicate of https://github.com/mswjs/msw/pull/403. There is also a PR that will be revisioned in the next days 🚀 . Stay tuned 💯

**Closed as completed by marcosvega91** 2020-10-02 21:13 UTC
Labels: bug
