### ISSUE TITLE
WARNING in ./node_modules/encoding/lib/iconv-loader

### ISSUE THREAD

**Issue by olegKusov** [mswjs/msw#490] opened 2020-12-02 23:34 UTC
## Environment

| Name | Version |
| ---- | ------- |
| msw  | 0.21.3   |
| node | 14     |
| OS   | macos 11     |

## Current behavior

in dev mode I have warning in console

## Expected behavior

I don't wanna see it

## Screenshots

![изображение](https://user-images.githubusercontent.com/28058268/100944242-e5232780-350f-11eb-8561-b4a351ad9b58.png)

**Comment by tigerabrodi** [comment] 2020-12-05 10:23
@kettanaito I took take a deeper look into this :+1:, also do you have any clues on what could be causing this?

**Comment by kettanaito** [comment] 2020-12-05 11:00
That'd be of much help, @tigerabrodi!

That dependency originates from `node-fetch` that MSW conditionally requires in NodeJS environment. 

```
- msw
  - node-fetch
    - encoding
      - iconv-loader
```

What is interesting, is that I don't experience this warning anywhere: local tests, reproduction repositories, example repositories, sandboxes.

**Comment by tigerabrodi** [comment] 2020-12-05 11:02
@kettanaito I wonder if it has something to do with @olegKusov Operating System or something like that?

It would be great if we could somehow reproduce this.

**Comment by kettanaito** [comment] 2020-12-05 11:17
Seems like they are using MacOS, so the operating system is unlikely to be the root cause. I'm thinking whether we should specify `node-fetch` as a tree-shackable/side-effect-free dependency of any sort so that webpack knows it doesn't have to transpile it if the end-user doesn't rely on it.

**Comment by tigerabrodi** [comment] 2020-12-05 18:29
@kettanaito Maybe we should add a label that this needs a reproduction?

**Comment by kettanaito** [comment] 2021-01-22 09:27
Sorry, there isn't much we can do without a reproduction repository. Feel free to include the way to reproduce, but until then I'm closing this as non-reproducible.

**Closed as completed by kettanaito** 2021-01-22 09:27 UTC
Labels: bug, scope:node, needs:reproduction
