### ISSUE TITLE
jest : Error: Error: connect ECONNREFUSED 127.0.0.1:80

### ISSUE THREAD

**Issue by ghost** [mswjs/msw#411] opened 2020-10-02 09:29 UTC
## Environment

| Name | Version |
| ---- | ------- |
| msw  | 0.21.2   |
| node | v14.11.0     |
| OS   | ubuntu-18.04     |

## Request handlers

```js
import { rest } from 'msw'
import { setupServer } from 'msw/node'
import { handlers } from './handlers'

const server = setupServer(...handlers)
export { server, rest }
```

## Actual request

```js
// Example of making a request. Provide your code here.
rest.get(API, async (req, res, ctx) => {
    const user = {
      user_metadata: {
        stream: {
          userId: 'john',
          accessToken: 'askdjklj389082',
        },
      },
    }
    return res(ctx.json(user))
  })
```

## Current behavior

My React Tests are working locally but the same tests at Github Actions are failing:

```      Error: Error: connect ECONNREFUSED 127.0.0.1:80 ```

## Expected behavior

Test shall pass.

**Comment by marcosvega91** [comment] 2020-10-02 10:03
Hi @j18s thanks for reaching us 😄 

I see that in your handler you are using `API` variable. What is the value in your CI ? We are using `MSW` with github actions without issues.

**Comment by kettanaito** [comment] 2020-10-07 09:44
The error implies that the request is not mocked. That can happen for multiple reasons:

- The URL you provide to the request handler does not correspond to the actual request URL. Double check the URL you are trying to capture for typos, parameters, or integrity.
- You are not returning anything from a request handler.
- You are doing explicit return in a request handler `return`.
- Your request handler throws at some point of execution. The error message shall be forwarded in the test process.

Please double check your handler and its `API` variable, start with hard-coding the request URL instead of using the variable. Let us know what you find out.

**Comment by kettanaito** [comment] 2020-10-09 09:45
Hey, @j18s. Please, did you have a chance to look at the questions/suggestions from @marcosvega91 and me above? We'd love to learn more about the issue you experience and assist you in resolving it. Please let us know!

**Comment by kettanaito** [comment] 2020-10-21 09:55
I'm closing this due to inactivity.

If you still experience this issue please create a reproduction repository or [a sandbox](https://codesandbox.io/s/goofy-darwin-xx1c8) and leave a comment with it here. The original issue is most likely due to the `API` variable not corresponding to the actual request URL, which produces a mismatch that results into an actual request being performed.

**Closed as completed by kettanaito** 2020-10-21 09:55 UTC
Labels: bug, scope:node, needs:reproduction
