### ISSUE TITLE
"Failed to register a Service Worker" when using "code-server"

### ISSUE THREAD

**Issue by epochfairy** [mswjs/msw#728] opened 2021-05-09 13:55 UTC
Uncaught (in promise) Error: [MSW] Failed to register a Service Worker: this browser does not support Service Workers (see https://caniuse.com/serviceworkers), or your application is running on an insecure host (consider using HTTPS for custom hostnames).

**Comment by epochfairy** [comment] 2021-05-09 13:58
When using code sever（https://github.com/cdr/code-server） for remote programming, run the program 
eg：rum in 109.109.109.109:3000
Report this error

**Comment by epochfairy** [comment] 2021-05-09 14:22
![image](https://user-images.githubusercontent.com/66505223/117575578-0cac9a80-b115-11eb-857d-04442384a489.png)

**Comment by kettanaito** [comment] 2021-05-10 12:52
Hey, @epochfairy.

It'd be appreciated if you filled in the issue template. It contains useful information for the library maintainers to help you solve the issue. 

The error is quite self-explanatory: you're either calling `setupWorker()` in a browser that doesn't support the Service Worker API (which is unlikely, as your screenshot implies Chrome), or your application's address cannot be directly used to register the worker (i.e. custom hostname, usage of HTTPS protocol locally).

I have a suspicion that since you're running an app on an absolute URL `109.109.109.109:3000` you need to specify the worker against that URL (using the [serviceWorker.url](https://mswjs.io/docs/api/setup-worker/start#serviceworker) option).

### Please provide the following details:

- Your OS (name, version).
- What browser are you using (name, build version).
- Your MSW setup: handlers, `setupWorker()` call.
- What is the `window.location` of your application when you're running it?
- **Please prepare a reproduction repository with the steps to get this error.**

**Comment by kettanaito** [comment] 2021-05-18 09:23
Closing this because the reproduction repository hasn't been provided.

As I've mentioned above, the issue is very likely to be how you serve your application locally. Ensure you're trusting insecure hosts in case of running it over local HTTPS, point to the correct worker script in case you're proxying your app in some way. 

Our team will be glad to look into this issue if you create a reproduction repository and link it here. Until then, there isn't much we can do.

**Closed as completed by kettanaito** 2021-05-18 09:23 UTC
Labels: bug, scope:browser, needs:reproduction
